(part "XT90PW-F"
    (packageRef "XT90PWF")
    (interface
        (port "1" (symbPinId 1) (portName "+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-") (portType INOUT))
        (port "3" (symbPinId 3) (portName "MH1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "MH2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "TME_Electronic_Components_Part_Number" "")
    (property "TME_Electronic_Components_Price/Stock" "")
    (property "Manufacturer_Name" "Amass")
    (property "Manufacturer_Part_Number" "XT90PW-F")
    (property "Description" "Connector: DC supply; socket; female; XT90; 40A; 500V; PIN: 2; THT")
    (property "Datasheet_Link" "https://www.tme.eu/Document/7357a049cc8e5ea73e34d2124a313a81/XT90PW.pdf")
    (property "symbolName1" "XT90PW-F")
)
