#pragma once
#include "constants.h"
#include <Arduino.h>

float CUMULATIVE_CELL_VOLTAGES[4]  = { NAN, NAN, NAN, NAN }; 

float INDIVIDUAL_CELL_VOLTAGES[4] = {
    CUMULATIVE_CELL_VOLTAGES[0],
    CUMULATIVE_CELL_VOLTAGES[1] - CUMULATIVE_CELL_VOLTAGES[0],
    CUMULATIVE_CELL_VOLTAGES[2] - CUMULATIVE_CELL_VOLTAGES[1],
    CUMULATIVE_CELL_VOLTAGES[3] - CUMULATIVE_CELL_VOLTAGES[2]
};   